# Site settings
title: Robin Wilson's books and reading journal, and other projects
motto: ""
email: rwilson@museum.vic.gov.au
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timeteam.github.io" # the base hostname & protocol for your site
# twitter_username: Neanthes
github_username:  timeteam

# Build settings
markdown: kramdown
