
# Site settings
name: "Robin Wilson"
title: Robin's books and reading
email: rwilson@museum.vic.gov.au
description: "Robin Wilson books and reading.  Mostly science and other non-fiction.  Some fiction."


# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
  music:
    output: true
